CREATE DATABASE lesson2;
USE lesson2;
CREATE TABLE users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age TINYINT(2) NOT NULL DEFAULT 18,
    PRIMARY KEY(id),
    UNIQUE KEY(email),
    UNIQUE KEY(login)
) ENGINE=InnoDB;